-- FinSentry Phase 2 schema.
-- Run this in the Supabase SQL Editor (Project -> SQL Editor -> New query) once,
-- against a fresh project. Safe to re-run: drops + recreates these four tables.

drop table if exists flags cascade;
drop table if exists analyses cascade;
drop table if exists videos cascade;
drop table if exists influencers cascade;

create table influencers (
  id           bigint generated by default as identity primary key,
  username     text not null unique,
  name         text not null,
  profile_url  text,
  followers    integer not null default 0,
  active       boolean not null default true,
  created_at   timestamptz not null default now()
);

create table videos (
  id             bigint generated by default as identity primary key,
  influencer_id  bigint not null references influencers(id) on delete cascade,
  reel_url       text not null unique,
  video_url      text,
  thumbnail_url  text,
  caption        text,
  posted_at      date,
  created_at     timestamptz not null default now()
);

create table analyses (
  id                    bigint generated by default as identity primary key,
  video_id              bigint not null references videos(id) on delete cascade,
  is_financial_content  boolean not null default false,
  stock                 text,
  ticker                text,
  recommendation        text check (recommendation in ('BUY', 'SELL', 'HOLD')),
  price_target          text,
  future_prediction     boolean not null default false,
  certainty             text check (certainty in ('LOW', 'MEDIUM', 'HIGH')),
  risk_score            integer not null default 0 check (risk_score between 0 and 100),
  risk_level            text not null default 'LOW' check (risk_level in ('LOW', 'REVIEW', 'HIGH', 'CRITICAL')),
  evidence              text,
  "timestamp"           text,
  score_breakdown       jsonb not null default '[]'::jsonb,
  raw_response          jsonb,
  created_at            timestamptz not null default now()
);

create table flags (
  id            bigint generated by default as identity primary key,
  analysis_id   bigint not null references analyses(id) on delete cascade,
  severity      text not null check (severity in ('REVIEW', 'HIGH', 'CRITICAL')),
  reason        text,
  reviewed      boolean not null default false,
  review_notes  text,
  created_at    timestamptz not null default now()
);

create index idx_videos_influencer_id on videos(influencer_id);
create index idx_analyses_video_id on analyses(video_id);
create index idx_flags_analysis_id on flags(analysis_id);

-- ---- Row Level Security -------------------------------------------------
-- The dashboard is an anonymous-key frontend with no login yet, so RLS here
-- is deliberately minimal: public read on everything (it's an internal review
-- tool), and public write ONLY on the one action the UI performs today --
-- marking a flag reviewed / saving review notes. Inserts to influencers,
-- videos, and analyses are meant to come from the scraper/Gemini pipeline
-- (Phases 3, 5, 6) using the service_role key, which bypasses RLS entirely --
-- so no anon insert policy is defined for those tables. Revisit once auth
-- exists (Phase 7/8).

alter table influencers enable row level security;
alter table videos enable row level security;
alter table analyses enable row level security;
alter table flags enable row level security;

create policy "Public read access" on influencers for select using (true);
create policy "Public read access" on videos for select using (true);
create policy "Public read access" on analyses for select using (true);
create policy "Public read access" on flags for select using (true);

create policy "Public can update flag review state" on flags
  for update using (true) with check (true);
